version: '3.8'

services:
  prime-luthieria:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prime-luthieria.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.prime-luthieria.entrypoints=websecure"
      - "traefik.http.routers.prime-luthieria.tls.certresolver=letsencrypt"
